from django.contrib.gis import admin
from models import * 

admin.site.register(Bicycle_Network_pdx, admin.OSMGeoAdmin)
admin.site.register(Storefront_Improvement_Areas_pdx, admin.OSMGeoAdmin)
admin.site.register(Bridges_pdx, admin.OSMGeoAdmin)
admin.site.register(Leaf_Pickup_pdx, admin.OSMGeoAdmin)
admin.site.register(Signage_Lighting_Imp_Prog_pdx, admin.OSMGeoAdmin)
admin.site.register(LID_Streets_pdx, admin.OSMGeoAdmin)
admin.site.register(Parks_Taxlots_pdx, admin.OSMGeoAdmin)
admin.site.register(Urban_Renewal_Area_pdx, admin.OSMGeoAdmin)
admin.site.register(Curbs_pdx, admin.OSMGeoAdmin)
admin.site.register(Parks_Easements_pdx, admin.OSMGeoAdmin)
admin.site.register(Business_Associations, admin.OSMGeoAdmin)
admin.site.register(Curb_Ramps_pdx, admin.OSMGeoAdmin)
admin.site.register(Parks_Vegetation_Survey_pdx, admin.OSMGeoAdmin)
admin.site.register(Pavement_Maint_pdx, admin.OSMGeoAdmin)
admin.site.register(Zoning_Arrows_pdx, admin.OSMGeoAdmin)
admin.site.register(Zoning_Lines_pdx, admin.OSMGeoAdmin)
admin.site.register(Zoning_Anno_pdx, admin.OSMGeoAdmin)
admin.site.register(Zoning_pdx, admin.OSMGeoAdmin)
admin.site.register(Parks_pdx, admin.OSMGeoAdmin)
admin.site.register(Bicycle_Parking_pdx, admin.OSMGeoAdmin)
admin.site.register(Heritage_Trees_pdx, admin.OSMGeoAdmin)
admin.site.register(Sidewalks_pdx, admin.OSMGeoAdmin)
admin.site.register(Guardrails_pdx, admin.OSMGeoAdmin)
admin.site.register(LID_Boundaries_pdx, admin.OSMGeoAdmin)
admin.site.register(TSP_Classifications_pdx, admin.OSMGeoAdmin)
admin.site.register(Development_Opp_Areas_pdx, admin.OSMGeoAdmin)
admin.site.register(Corner_Improved_pdx, admin.OSMGeoAdmin)
admin.site.register(TSP_District_Boundaries_pdx, admin.OSMGeoAdmin)
admin.site.register(Parks_Desired_Fut_Cond_pdx, admin.OSMGeoAdmin)
admin.site.register(Homebuyer_Opp_Area_pdx, admin.OSMGeoAdmin)
admin.site.register(Transit_Stations_pdx, admin.OSMGeoAdmin)
admin.site.register(Pavement_Moratorium_pdx, admin.OSMGeoAdmin)
admin.site.register(ZipCodes_pdx, admin.OSMGeoAdmin)
admin.site.register(Parks_Trails_pdx, admin.OSMGeoAdmin)
